/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NotificacoesRouteImport } from './routes/notificacoes'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ExplorarRouteImport } from './routes/explorar'
import { Route as CriadoresRouteImport } from './routes/criadores'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoteirosIndexRouteImport } from './routes/roteiros.index'
import { Route as PublicarIndexRouteImport } from './routes/publicar.index'
import { Route as PerfilIndexRouteImport } from './routes/perfil.index'
import { Route as PublicarRoteiroRouteImport } from './routes/publicar.roteiro'
import { Route as PublicarPostRouteImport } from './routes/publicar.post'
import { Route as PerfilAjustesRouteImport } from './routes/perfil.ajustes'
import { Route as LocalIdRouteImport } from './routes/local.$id'
import { Route as RoteirosIdIndexRouteImport } from './routes/roteiros.$id.index'
import { Route as RoteirosIdParadaStopIdRouteImport } from './routes/roteiros.$id.parada.$stopId'

const NotificacoesRoute = NotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorarRoute = ExplorarRouteImport.update({
  id: '/explorar',
  path: '/explorar',
  getParentRoute: () => rootRouteImport,
} as any)
const CriadoresRoute = CriadoresRouteImport.update({
  id: '/criadores',
  path: '/criadores',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoteirosIndexRoute = RoteirosIndexRouteImport.update({
  id: '/roteiros/',
  path: '/roteiros/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicarIndexRoute = PublicarIndexRouteImport.update({
  id: '/publicar/',
  path: '/publicar/',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilIndexRoute = PerfilIndexRouteImport.update({
  id: '/perfil/',
  path: '/perfil/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicarRoteiroRoute = PublicarRoteiroRouteImport.update({
  id: '/publicar/roteiro',
  path: '/publicar/roteiro',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicarPostRoute = PublicarPostRouteImport.update({
  id: '/publicar/post',
  path: '/publicar/post',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilAjustesRoute = PerfilAjustesRouteImport.update({
  id: '/perfil/ajustes',
  path: '/perfil/ajustes',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalIdRoute = LocalIdRouteImport.update({
  id: '/local/$id',
  path: '/local/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RoteirosIdIndexRoute = RoteirosIdIndexRouteImport.update({
  id: '/roteiros/$id/',
  path: '/roteiros/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoteirosIdParadaStopIdRoute = RoteirosIdParadaStopIdRouteImport.update({
  id: '/roteiros/$id/parada/$stopId',
  path: '/roteiros/$id/parada/$stopId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/criadores': typeof CriadoresRoute
  '/explorar': typeof ExplorarRoute
  '/login': typeof LoginRoute
  '/notificacoes': typeof NotificacoesRoute
  '/local/$id': typeof LocalIdRoute
  '/perfil/ajustes': typeof PerfilAjustesRoute
  '/publicar/post': typeof PublicarPostRoute
  '/publicar/roteiro': typeof PublicarRoteiroRoute
  '/perfil/': typeof PerfilIndexRoute
  '/publicar/': typeof PublicarIndexRoute
  '/roteiros/': typeof RoteirosIndexRoute
  '/roteiros/$id/': typeof RoteirosIdIndexRoute
  '/roteiros/$id/parada/$stopId': typeof RoteirosIdParadaStopIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/criadores': typeof CriadoresRoute
  '/explorar': typeof ExplorarRoute
  '/login': typeof LoginRoute
  '/notificacoes': typeof NotificacoesRoute
  '/local/$id': typeof LocalIdRoute
  '/perfil/ajustes': typeof PerfilAjustesRoute
  '/publicar/post': typeof PublicarPostRoute
  '/publicar/roteiro': typeof PublicarRoteiroRoute
  '/perfil': typeof PerfilIndexRoute
  '/publicar': typeof PublicarIndexRoute
  '/roteiros': typeof RoteirosIndexRoute
  '/roteiros/$id': typeof RoteirosIdIndexRoute
  '/roteiros/$id/parada/$stopId': typeof RoteirosIdParadaStopIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/criadores': typeof CriadoresRoute
  '/explorar': typeof ExplorarRoute
  '/login': typeof LoginRoute
  '/notificacoes': typeof NotificacoesRoute
  '/local/$id': typeof LocalIdRoute
  '/perfil/ajustes': typeof PerfilAjustesRoute
  '/publicar/post': typeof PublicarPostRoute
  '/publicar/roteiro': typeof PublicarRoteiroRoute
  '/perfil/': typeof PerfilIndexRoute
  '/publicar/': typeof PublicarIndexRoute
  '/roteiros/': typeof RoteirosIndexRoute
  '/roteiros/$id/': typeof RoteirosIdIndexRoute
  '/roteiros/$id/parada/$stopId': typeof RoteirosIdParadaStopIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastro'
    | '/criadores'
    | '/explorar'
    | '/login'
    | '/notificacoes'
    | '/local/$id'
    | '/perfil/ajustes'
    | '/publicar/post'
    | '/publicar/roteiro'
    | '/perfil/'
    | '/publicar/'
    | '/roteiros/'
    | '/roteiros/$id/'
    | '/roteiros/$id/parada/$stopId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/criadores'
    | '/explorar'
    | '/login'
    | '/notificacoes'
    | '/local/$id'
    | '/perfil/ajustes'
    | '/publicar/post'
    | '/publicar/roteiro'
    | '/perfil'
    | '/publicar'
    | '/roteiros'
    | '/roteiros/$id'
    | '/roteiros/$id/parada/$stopId'
  id:
    | '__root__'
    | '/'
    | '/cadastro'
    | '/criadores'
    | '/explorar'
    | '/login'
    | '/notificacoes'
    | '/local/$id'
    | '/perfil/ajustes'
    | '/publicar/post'
    | '/publicar/roteiro'
    | '/perfil/'
    | '/publicar/'
    | '/roteiros/'
    | '/roteiros/$id/'
    | '/roteiros/$id/parada/$stopId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CadastroRoute: typeof CadastroRoute
  CriadoresRoute: typeof CriadoresRoute
  ExplorarRoute: typeof ExplorarRoute
  LoginRoute: typeof LoginRoute
  NotificacoesRoute: typeof NotificacoesRoute
  LocalIdRoute: typeof LocalIdRoute
  PerfilAjustesRoute: typeof PerfilAjustesRoute
  PublicarPostRoute: typeof PublicarPostRoute
  PublicarRoteiroRoute: typeof PublicarRoteiroRoute
  PerfilIndexRoute: typeof PerfilIndexRoute
  PublicarIndexRoute: typeof PublicarIndexRoute
  RoteirosIndexRoute: typeof RoteirosIndexRoute
  RoteirosIdIndexRoute: typeof RoteirosIdIndexRoute
  RoteirosIdParadaStopIdRoute: typeof RoteirosIdParadaStopIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/notificacoes': {
      id: '/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof NotificacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorar': {
      id: '/explorar'
      path: '/explorar'
      fullPath: '/explorar'
      preLoaderRoute: typeof ExplorarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criadores': {
      id: '/criadores'
      path: '/criadores'
      fullPath: '/criadores'
      preLoaderRoute: typeof CriadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roteiros/': {
      id: '/roteiros/'
      path: '/roteiros'
      fullPath: '/roteiros/'
      preLoaderRoute: typeof RoteirosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publicar/': {
      id: '/publicar/'
      path: '/publicar'
      fullPath: '/publicar/'
      preLoaderRoute: typeof PublicarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil/': {
      id: '/perfil/'
      path: '/perfil'
      fullPath: '/perfil/'
      preLoaderRoute: typeof PerfilIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publicar/roteiro': {
      id: '/publicar/roteiro'
      path: '/publicar/roteiro'
      fullPath: '/publicar/roteiro'
      preLoaderRoute: typeof PublicarRoteiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publicar/post': {
      id: '/publicar/post'
      path: '/publicar/post'
      fullPath: '/publicar/post'
      preLoaderRoute: typeof PublicarPostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil/ajustes': {
      id: '/perfil/ajustes'
      path: '/perfil/ajustes'
      fullPath: '/perfil/ajustes'
      preLoaderRoute: typeof PerfilAjustesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/local/$id': {
      id: '/local/$id'
      path: '/local/$id'
      fullPath: '/local/$id'
      preLoaderRoute: typeof LocalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roteiros/$id/': {
      id: '/roteiros/$id/'
      path: '/roteiros/$id'
      fullPath: '/roteiros/$id/'
      preLoaderRoute: typeof RoteirosIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roteiros/$id/parada/$stopId': {
      id: '/roteiros/$id/parada/$stopId'
      path: '/roteiros/$id/parada/$stopId'
      fullPath: '/roteiros/$id/parada/$stopId'
      preLoaderRoute: typeof RoteirosIdParadaStopIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CadastroRoute: CadastroRoute,
  CriadoresRoute: CriadoresRoute,
  ExplorarRoute: ExplorarRoute,
  LoginRoute: LoginRoute,
  NotificacoesRoute: NotificacoesRoute,
  LocalIdRoute: LocalIdRoute,
  PerfilAjustesRoute: PerfilAjustesRoute,
  PublicarPostRoute: PublicarPostRoute,
  PublicarRoteiroRoute: PublicarRoteiroRoute,
  PerfilIndexRoute: PerfilIndexRoute,
  PublicarIndexRoute: PublicarIndexRoute,
  RoteirosIndexRoute: RoteirosIndexRoute,
  RoteirosIdIndexRoute: RoteirosIdIndexRoute,
  RoteirosIdParadaStopIdRoute: RoteirosIdParadaStopIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
